### ISSUE TITLE
Allow paper-icon-button with real link (anchor tags)

### ISSUE THREAD

**Issue by clyfe** [Polymer/paper-icon-button#13]
Like this:

``` html
<paper-icon-button icon="cloud-download">
  <a href="#download" target="_self"></a>
</paper-icon-button>
```

Ref: https://github.com/Polymer/paper-tabs/issues/32

**Comment by Roysvork** [comment]
Just a note that this is inconsistent with paper-button. Ideally these two would behave in the same way so this may want to be revisited. 

https://www.polymer-project.org/0.5/components/paper-button/demo.html

**Comment by omtinez** [comment]
I agree with @beyond-code-github. Can we reopen this issue?

**Comment by pik** [comment]
This isn't good 

```html
<a href="https://www.polymer-project.org" target="_blank" class="inherit">
    <paper-icon-button icon="polymer" title="polymer"></paper-icon-button>
</a>
```

Because the icon-button can actually be bigger than the `<a>` link box. Would be nice to have a clean way to do it without additional CSS fiddling.

**Comment by davidmaxwaterman** [comment]
My view is that wrapping a button in an anchor isn't a good solution. For example, I wonder how to disable the button effectively.
