### ISSUE TITLE
box-sizing: border-box makes icons tiny

### ISSUE THREAD

**Issue by atotic** [Polymer/paper-icon-button#27]
If you are using `box-sizing: border-box` globally, paper-icon-button icons are tiny.

This fixes it:

```
    --paper-icon-button: {
      box-sizing: content-box;
    }
```

You might want to specify box-sizing explicitly by default, because global border-box is fashionable.

**Comment by notwaldorf** [comment]
@atotic is this on the 0.5 element, or on the 1.0 one? (at PolymerElements/paper-icon-button :smile:)

**Comment by atotic** [comment]
Oops, got bitten by this again. Just refiled in the proper place. This happened after today's bower update.
